use super::*;

pub fn patterns() -> Vec<CleanupPattern> {
    vec![
        CleanupPattern {
            id: "xcode-derived-data",
            category: CleanupCategory::DevTools,
            name: "Xcode Derived Data",
            description: "Build artifacts and index data generated by Xcode. Safe to delete; Xcode will rebuild as needed.",
            risk_level: RiskLevel::Safe,
            detection: DetectionMethod::KnownPath {
                path: "~/Library/Developer/Xcode/DerivedData",
                expandable: true,
            },
            cleanup: CleanupMethod::Delete { use_trash: true },
        },
        CleanupPattern {
            id: "xcode-archives",
            category: CleanupCategory::DevTools,
            name: "Xcode Archives",
            description: "Archived builds for App Store submission. Review before deleting as they may contain release builds.",
            risk_level: RiskLevel::Caution,
            detection: DetectionMethod::KnownPath {
                path: "~/Library/Developer/Xcode/Archives",
                expandable: true,
            },
            cleanup: CleanupMethod::OpenInFinder,
        },
        CleanupPattern {
            id: "xcode-device-support",
            category: CleanupCategory::DevTools,
            name: "Xcode iOS Device Support",
            description: "Debug symbols for connected iOS devices. Safe to delete; re-downloaded when device is reconnected.",
            risk_level: RiskLevel::Safe,
            detection: DetectionMethod::KnownPath {
                path: "~/Library/Developer/Xcode/iOS DeviceSupport",
                expandable: true,
            },
            cleanup: CleanupMethod::Delete { use_trash: true },
        },
        CleanupPattern {
            id: "xcode-simulators",
            category: CleanupCategory::DevTools,
            name: "Xcode Unavailable Simulators",
            description: "Simulator runtimes for old iOS versions that are no longer available. Safe to remove.",
            risk_level: RiskLevel::Safe,
            detection: DetectionMethod::Command {
                check_cmd: "xcrun simctl list devices unavailable 2>/dev/null | grep -c 'unavailable' || echo 0",
                parse_hint: "count_lines",
            },
            cleanup: CleanupMethod::ShellCommand {
                command: "xcrun simctl delete unavailable".to_string(),
                run_in_terminal: true,
                refresh_after: false,
            },
        },
        CleanupPattern {
            id: "xcode-simulator-runtimes",
            category: CleanupCategory::DevTools,
            name: "Xcode Simulator Runtime Images",
            description: "Downloaded iOS/watchOS/tvOS simulator runtime disk images (5-8GB each). Stored in /Library/Developer/CoreSimulator/Images/ and /System/Library/AssetsV2/. Delete old versions you no longer need.",
            risk_level: RiskLevel::Caution,
            detection: DetectionMethod::Command {
                check_cmd: "xcrun simctl runtime list 2>/dev/null | tail -1 | grep -oE '[0-9]+\\.[0-9]+G' || echo 0",
                parse_hint: "total_size",
            },
            cleanup: CleanupMethod::ShellCommand {
                command: "echo 'Installed simulator runtimes:' && echo '' && xcrun simctl runtime list && echo '' && echo 'To delete a runtime, run:' && echo '  xcrun simctl runtime delete <identifier>' && echo '' && echo 'Example:' && echo '  xcrun simctl runtime delete iOS-17-0'".to_string(),
                run_in_terminal: true,
                refresh_after: false,
            },
        },
        CleanupPattern {
            id: "xcode-spm-cache",
            category: CleanupCategory::DevTools,
            name: "Swift Package Manager Cache",
            description: "Cached Swift package checkouts and artifacts. Safe to delete; re-downloaded on next build.",
            risk_level: RiskLevel::Safe,
            detection: DetectionMethod::KnownPath {
                path: "~/Library/Caches/org.swift.swiftpm",
                expandable: true,
            },
            cleanup: CleanupMethod::Delete { use_trash: true },
        },
        CleanupPattern {
            id: "cargo-target",
            category: CleanupCategory::DevTools,
            name: "Rust Cargo Target Dirs",
            description: "Rust compilation artifacts in project target directories. Safe to delete; rebuilt on next cargo build.",
            risk_level: RiskLevel::Safe,
            detection: DetectionMethod::PathPattern {
                dir_name: Some("target"),
                path_contains: None,
                parent_marker: Some("Cargo.toml"),
            },
            cleanup: CleanupMethod::Delete { use_trash: true },
        },
        CleanupPattern {
            id: "gradle-cache",
            category: CleanupCategory::DevTools,
            name: "Gradle Cache",
            description: "Cached Gradle build dependencies and artifacts. Safe to delete; re-downloaded on next build.",
            risk_level: RiskLevel::Safe,
            detection: DetectionMethod::KnownPath {
                path: "~/.gradle/caches",
                expandable: true,
            },
            cleanup: CleanupMethod::Delete { use_trash: true },
        },
        CleanupPattern {
            id: "maven-repo",
            category: CleanupCategory::DevTools,
            name: "Maven Local Repository",
            description: "Locally cached Maven artifacts. Safe to delete; re-downloaded on next build.",
            risk_level: RiskLevel::Safe,
            detection: DetectionMethod::KnownPath {
                path: "~/.m2/repository",
                expandable: true,
            },
            cleanup: CleanupMethod::Delete { use_trash: true },
        },
        CleanupPattern {
            id: "android-sdk",
            category: CleanupCategory::DevTools,
            name: "Android SDK",
            description: "Android SDK files including platform tools and system images. Review before deleting.",
            risk_level: RiskLevel::Caution,
            detection: DetectionMethod::KnownPath {
                path: "~/Library/Android/sdk",
                expandable: true,
            },
            cleanup: CleanupMethod::OpenInFinder,
        },
    ]
}
